/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jhshoes;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListModel;

/**
 *
 * @author narissacooney
 */
public class ShoeDisplay extends javax.swing.JFrame {

    // The product to display
    private final Product product;
    private final DefaultListModel<Product> listBasketItems;

    /**
     * Creates new form WomensShoes
     */
    public ShoeDisplay(Product product, DefaultListModel<Product> listBasketItems) {
        this.product = product;
        this.listBasketItems = listBasketItems;
        initComponents();

        txtShoeDescription.setText(product.getProductDescription());
        txtShoeProductID.setText(String.valueOf(product.getProductID()));
        txtShoeProductPrice.setText(String.valueOf(product.getProductPrice()));
        txtShoeProductQuantity.setText(String.valueOf(product.getProductQuantity()));
        txtShoeGender.setText(String.valueOf(product.getGender()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblShoeProductID = new javax.swing.JLabel();
        lblShoeProductPrice = new javax.swing.JLabel();
        lblShoeProductQuantity = new javax.swing.JLabel();
        lblShoeDescription = new javax.swing.JLabel();
        lblShoeGender = new javax.swing.JLabel();
        lblShoeSize = new javax.swing.JLabel();
        txtShoeProductID = new javax.swing.JTextField();
        txtShoeProductPrice = new javax.swing.JTextField();
        txtShoeProductQuantity = new javax.swing.JTextField();
        txtShoeDescription = new javax.swing.JTextField();
        txtShoeGender = new javax.swing.JTextField();
        txtShoeSize = new javax.swing.JTextField();
        btnAddToBasket = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        lblShoeProductID.setText("Product ID");

        lblShoeProductPrice.setText("Product Price");

        lblShoeProductQuantity.setText("Product Quantity");

        lblShoeDescription.setText("Description");

        lblShoeGender.setText("Gender");

        lblShoeSize.setText("Size");

        txtShoeProductID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShoeProductIDActionPerformed(evt);
            }
        });

        txtShoeProductQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShoeProductQuantityActionPerformed(evt);
            }
        });

        txtShoeSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShoeSizeActionPerformed(evt);
            }
        });

        btnAddToBasket.setText("Add To Basket");
        btnAddToBasket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToBasketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblShoeSize)
                    .addComponent(lblShoeGender)
                    .addComponent(lblShoeDescription)
                    .addComponent(lblShoeProductQuantity)
                    .addComponent(lblShoeProductPrice)
                    .addComponent(lblShoeProductID))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtShoeProductID, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(txtShoeProductPrice)
                    .addComponent(txtShoeProductQuantity)
                    .addComponent(txtShoeDescription)
                    .addComponent(txtShoeGender)
                    .addComponent(txtShoeSize))
                .addGap(48, 48, 48)
                .addComponent(btnAddToBasket)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblShoeProductID)
                            .addComponent(txtShoeProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblShoeProductPrice)
                            .addComponent(txtShoeProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblShoeProductQuantity))
                    .addComponent(txtShoeProductQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShoeDescription)
                    .addComponent(txtShoeDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblShoeGender)
                    .addComponent(txtShoeGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblShoeSize)
                            .addComponent(txtShoeSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(btnAddToBasket)
                        .addGap(17, 17, 17))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtShoeProductIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShoeProductIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShoeProductIDActionPerformed

    private void txtShoeProductQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShoeProductQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShoeProductQuantityActionPerformed

    private void txtShoeSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShoeSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShoeSizeActionPerformed

    private void btnAddToBasketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToBasketActionPerformed
        listBasketItems.addElement(product);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddToBasketActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToBasket;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblShoeDescription;
    private javax.swing.JLabel lblShoeGender;
    private javax.swing.JLabel lblShoeProductID;
    private javax.swing.JLabel lblShoeProductPrice;
    private javax.swing.JLabel lblShoeProductQuantity;
    private javax.swing.JLabel lblShoeSize;
    private javax.swing.JTextField txtShoeDescription;
    private javax.swing.JTextField txtShoeGender;
    private javax.swing.JTextField txtShoeProductID;
    private javax.swing.JTextField txtShoeProductPrice;
    private javax.swing.JTextField txtShoeProductQuantity;
    private javax.swing.JTextField txtShoeSize;
    // End of variables declaration//GEN-END:variables

    //creating close method
    private void close() {
        WindowEvent winClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
    }
}
